version: '3.8'

services:
  mongo-tx:
    image: mongo:7.0
    container_name: local_mongo_tx
    # Bên trong container vẫn chạy 27017
    command: ['--replSet', 'rs0', '--bind_ip_all', '--port', '27017']
    ports:
      - '27018:27017' # Ánh xạ cổng 27018 của máy tính vào 27017 của Docker
    volumes:
      - local_mongo_data:/data/db
    healthcheck:
      test: mongosh --port 27017 --quiet --eval "try { rs.initiate({_id:'rs0',members:[{_id:0,host:'127.0.0.1:27017'}]}) } catch(e) { rs.status().ok }"
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  redis:
    image: redis:7-alpine
    container_name: local_redis
    ports:
      - '6379:6379'
    volumes:
      - local_redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s

volumes:
  local_mongo_data:
  local_redis_data:
