name: CI/CD Fullstack Application

on:
  push:
    branches: [main]

jobs:
  backend-ci:
    name: Run Node.js Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./nodejs 
    strategy:
      matrix:
        node-version: [20.x] # Thường chỉ cần bản ổn định nhất để tiết kiệm thời gian,  18.x, 16.x, 14.x, 12.x, 10.x
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: './nodejs/package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint || echo "Linting failed but continuing..."

      - name: Run tests
        run: npm test || echo "No tests found"

  build-and-push:
    name: Build and Push Backend Docker
    runs-on: ubuntu-latest
    needs: backend-ci
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Backend image
        uses: docker/build-push-action@v6
        with:
          context: ./nodejs
          push: true
          platforms: linux/amd64
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKERHUB_PROJECT_NAME }}:latest
            ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKERHUB_PROJECT_NAME }}:${{ github.sha }}

  deploy-backend:
  name: Deploy Backend to VPS
  runs-on: ubuntu-latest
  needs: build-and-push

  steps:
    - name: SSH Deploy Backend
      uses: appleboy/ssh-action@v1.0.3

      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.VPS_PORT }}

        script: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

          docker pull ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKERHUB_PROJECT_NAME }}:latest

          docker stop ez_api || true
          docker rm ez_api || true

          docker network ls | grep ez-network || docker network create ez-network

          docker run -d \
            --name ez_api \
            --restart always \
            --network ez-network \
            -p 3000:3000 \
            -e NODE_ENV=production \
            -e MONGODB_URI="mongodb://mongo:27017/ezcheckin_prod?replicaSet=rs0" \
            -e MONGODB_MIGRATE_URI="mongodb://mongo:27017/?replicaSet=rs0" \
            -e MONGODB_DB_NAME="ezcheckin_prod" \
            -e SECRET_COOKIE="${{ secrets.SECRET_COOKIE }}" \
            -e JWT_ACCESS_SECRET="${{ secrets.JWT_ACCESS_SECRET }}" \
            -e JWT_REFRESH_SECRET="${{ secrets.JWT_REFRESH_SECRET }}" \
            -e EXPIRED_ACCESS_TOKEN="1d" \
            -e CLIENT_ORIGIN="${{ secrets.CLIENT_ORIGIN }}" \
            ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKERHUB_PROJECT_NAME }}:latest

              
  frontend-deploy:
    name: Build & Deploy Frontend
    runs-on: ubuntu-latest
    needs: deploy-backend # QUAN TRỌNG: Đợi Backend xong mới chạy
    defaults:
      run:
        working-directory: ./react-nextjs-nodejs 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Next.js Image
        uses: docker/build-push-action@v6
        with:
          context: ./react-nextjs-nodejs
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKERHUB_PROJECT_NAME_REACT }}:latest
            ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKERHUB_PROJECT_NAME_REACT }}:${{ github.sha }}

      - name: SSH Deploy Frontend
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
            docker pull ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKERHUB_PROJECT_NAME_REACT }}:latest
            docker stop ${{ secrets.DOCKERHUB_PROJECT_NAME_REACT }} || true
            docker rm ${{ secrets.DOCKERHUB_PROJECT_NAME_REACT }} || true

            docker run -d \
              --name ${{ secrets.DOCKERHUB_PROJECT_NAME_REACT }} \
              --restart always \
              --network app-net \
              -p 3000:3000 \
              -e NODE_ENV=production \
              -e NEXT_PUBLIC_API_URL_SOCKET=http://${{ secrets.DOCKERHUB_PROJECT_NAME }}:9000 \
              ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKERHUB_PROJECT_NAME_REACT }}:latest